#!/usr/bin/env bash
set -euo pipefail

script_directory="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(CDPATH= cd -- "$script_directory/.." && pwd)"

usage() {
    cat >&2 <<'USAGE'
usage: release.sh package VERSION BINARY OUTPUT_DIRECTORY
       release.sh formula VERSION OWNER/REPOSITORY ARCHIVE_DIRECTORY

VERSION is a release number such as 0.1.0, without the v prefix.
package creates one macOS archive; formula reads both CPU archives and writes Ruby to stdout.
USAGE
}

if [[ "$#" -eq 1 && ( "$1" == "--help" || "$1" == "-h" ) ]]; then
    usage
    exit 0
fi
if [[ "$#" -ne 4 ]]; then
    usage
    exit 2
fi

command_name="$1"
version="$2"
if [[ ! "$version" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
    echo "version must be MAJOR.MINOR.PATCH without a v prefix or leading zeroes" >&2
    exit 2
fi

case "$command_name" in
    package)
        binary="$3"
        output_directory="$4"
        if [[ ! -f "$binary" || ! -x "$binary" || -L "$binary" ]]; then
            echo "release input must be a regular executable, not a symlink" >&2
            exit 1
        fi
        if ! architecture="$(xcrun lipo -archs "$binary" 2>/dev/null)"; then
            echo "release input must be a Mach-O executable" >&2
            exit 1
        fi
        case "$architecture" in
            arm64|x86_64) ;;
            *)
                echo "release input must contain a single arm64 or x86_64 architecture" >&2
                exit 1
                ;;
        esac
        codesign --verify --strict "$binary"

        archive_name="codex-switch-$version-macos-$architecture.tar.gz"
        archive_path="$output_directory/$archive_name"
        if [[ -e "$archive_path" || -L "$archive_path" ]]; then
            echo "release archive already exists; use an empty output directory" >&2
            exit 1
        fi
        mkdir -p "$output_directory"
        staging_directory="$(mktemp -d "$output_directory/.release.XXXXXX")"
        trap 'rm -rf -- "$staging_directory"' EXIT
        mkdir "$staging_directory/package"
        install -m 0755 "$binary" "$staging_directory/package/codex-switch"
        install -m 0644 "$repository_root/LICENSE" "$staging_directory/package/LICENSE"
        codesign --verify --strict "$staging_directory/package/codex-switch"
        COPYFILE_DISABLE=1 tar --uid 0 --gid 0 --uname root --gname wheel \
            -czf "$staging_directory/$archive_name" \
            -C "$staging_directory/package" codex-switch LICENSE
        # A hard link publishes the completed archive without replacing an existing release.
        ln "$staging_directory/$archive_name" "$archive_path"
        echo "Packaged: $archive_name"
        ;;
    formula)
        repository="$3"
        archive_directory="$4"
        if [[ ! "$repository" =~ ^[A-Za-z0-9][A-Za-z0-9-]*/[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
            echo "repository must be OWNER/REPOSITORY on github.com" >&2
            exit 2
        fi
        for architecture in arm64 x86_64; do
            archive="$archive_directory/codex-switch-$version-macos-$architecture.tar.gz"
            if [[ ! -f "$archive" || -L "$archive" ]]; then
                echo "missing release archive for $architecture" >&2
                exit 1
            fi
        done
        arm_digest="$(shasum -a 256 "$archive_directory/codex-switch-$version-macos-arm64.tar.gz" | awk '{print $1}')"
        intel_digest="$(shasum -a 256 "$archive_directory/codex-switch-$version-macos-x86_64.tar.gz" | awk '{print $1}')"
        cat <<FORMULA
# Generated by scripts/release.sh; update it from the release archives.
class CodexSwitch < Formula
  desc "Switch local Codex accounts using macOS Keychain"
  homepage "https://github.com/$repository"
  version "$version"
  license "MIT"

  on_arm do
    url "https://github.com/$repository/releases/download/v$version/codex-switch-$version-macos-arm64.tar.gz"
    sha256 "$arm_digest"
  end

  on_intel do
    url "https://github.com/$repository/releases/download/v$version/codex-switch-$version-macos-x86_64.tar.gz"
    sha256 "$intel_digest"
  end

  depends_on macos: :sonoma

  def install
    bin.install "codex-switch"
  end

  test do
    assert_match "codex-switch [setup|add|list|recover|help]", shell_output("#{bin}/codex-switch help")
  end
end
FORMULA
        ;;
    *)
        usage
        exit 2
        ;;
esac
